[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1"
[window]
decorations = "None"
opacity = 0.90

[font]
normal = {family="FiraCode Nerd Font Mono", style="Regular" }
bold = {family="FiraCode Nerd Font Mono", style="Bold" }
size = 10

[keyboard]
bindings = [
    {key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
    {key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" }
]
